In [2]:
import numpy as np


In [3]:
# 1. Create a 3D Numpy array of shape (2,3,4) filled with integers from 1 to 24, and reshape it without using lopp
arr = np.arange(1,25).reshape(2,3,4)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [4]:
# 2. Generate a 5x5 array with random integers between 10 and 50, then extract all even numbers ussing boolean masking.
arr = np.random.randint(10,50,size=(5,5))
even_arr = arr[arr%2 == 0]
print(arr)
print("\n Even num :",even_arr)

[[40 23 37 29 39]
 [39 32 36 16 19]
 [48 10 38 29 28]
 [30 45 23 37 49]
 [20 14 33 27 37]]

 Even num : [40 32 36 16 48 10 38 28 30 20 14]


In [5]:
#3. Create two arrays a = np.arange(1,13).reshape (3,4) and b = np.array([10,20,30,40]) Use broadcasting to add b to every row of a
a = np.arange(1,13).reshape(3,4)
b = np.array([10,20,30,40])
print(a+b)

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [6]:
# 4. Construct a 6x6 identtity matrix and replace its secondary diagonal (from top-right to bottom-left) with all 7's
import numpy as np
arr = np.eye(6)
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [7]:
# 5 . Generate 20 linearly spaced numbers between -5 and 5. Reshape into a (4,5) array and extract only the element greater than 0
arr = np.linspace(-5,5,20).reshape(4,5)
print(arr)
print("\n")
print(arr[arr>0])

[[-5.         -4.47368421 -3.94736842 -3.42105263 -2.89473684]
 [-2.36842105 -1.84210526 -1.31578947 -0.78947368 -0.26315789]
 [ 0.26315789  0.78947368  1.31578947  1.84210526  2.36842105]
 [ 2.89473684  3.42105263  3.94736842  4.47368421  5.        ]]


[0.26315789 0.78947368 1.31578947 1.84210526 2.36842105 2.89473684
 3.42105263 3.94736842 4.47368421 5.        ]


In [8]:
# 6. Create 4x4 array with numbers from 1 to 16. Swapthe first and last rows using slicing.
ar6 = np.arange(1,17).reshape(4,4)
print(ar6,"\n")
ar6[[0,-1]] = ar6[[-1,0]]
print(ar6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[13 14 15 16]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [11]:
# 7. Create a 10×10 array with random floats between 0 and 1, then find the row with the maximum sum.
arr = np.random.rand(10, 10)
print(arr)
max_row = np.argmax(np.sum(arr, axis=1))
print(max_row)
print(arr[max_row])

[[0.05716498 0.95287005 0.72227793 0.21081726 0.70815113 0.73605495
  0.89930087 0.58641105 0.71343532 0.21664439]
 [0.8510055  0.86660702 0.45187925 0.95349264 0.85024794 0.39388658
  0.59956594 0.16752995 0.95576669 0.25945312]
 [0.71228867 0.92057429 0.56277462 0.86053242 0.49284464 0.99585239
  0.23458711 0.19138296 0.9063325  0.2448693 ]
 [0.55475086 0.37103481 0.91717537 0.40212253 0.06990026 0.84224983
  0.92817219 0.70215118 0.67410307 0.31359486]
 [0.50843476 0.06909946 0.90323549 0.84227788 0.82662067 0.19133344
  0.2529076  0.54979725 0.07627654 0.49120666]
 [0.48711031 0.27868864 0.41594025 0.18693895 0.79657466 0.4933882
  0.19208704 0.62330989 0.44859234 0.82671856]
 [0.38724017 0.10199477 0.64297728 0.84900022 0.86280601 0.26793114
  0.24482896 0.34521589 0.34639796 0.62239696]
 [0.04361473 0.38254919 0.67514107 0.92422342 0.25759973 0.64525209
  0.07197283 0.95968163 0.78663369 0.218043  ]
 [0.65163855 0.28595247 0.64557115 0.78640636 0.36234605 0.80815541
  0.13384279 

In [23]:
# 8. Given arr = np.arange(1,26).reshape(5,5), extract the submatrix of even numbers only, keeping their 2D structure.
arr = np.arange(1,26).reshape(5,5)
even = np.where(arr % 2 ==0 , arr , 0)
print("Submatrix with even number:")
print(even)

Submatrix with even number:
[[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


In [24]:
# 9. Generate two arrays a = np.array([1,2,3]) and b = np.array([[10],[20],[30]]). Perform multiplication using broadcasting and explain the result
j = np.array([1,2,3])
p = np.array([[10],[20],[30]])
print(j*p)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [27]:
# 10. Create a diagonal matrix with values [5,10,15,20]. Then convert it into a full 4×4 matrix where diagonal values remain but others are filled with -1.
J_diag = [5,10,15,20]
arr = np.full((4,4),-1)
np.fill_diagonal(arr,J_diag)
print(arr)

[[ 5 -1 -1 -1]
 [-1 10 -1 -1]
 [-1 -1 15 -1]
 [-1 -1 -1 20]]


In [28]:
# 11. Using np.eye(5), create a 5×5 matrix with diagonal values equal to multiples of 3
arr = np.eye(5)
np.fill_diagonal(arr,3)
print(arr)

[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]


In [29]:
# 12. Construct an array of shape (3,4,2) with values from 1 to 24. Flatten it using ravel(), and then reshape it into (2,3,4).
A = np.arange(1,25).reshape(3,4,2)
print(A)
print("\n")
print(A.ravel())
print("\n")
print(A.reshape(2,3,4))

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [30]:
# 13.Generate a 7×7 matrix of random integers (1–100). Replace all values divisible by 5 with -5 using boolean indexing.
matrix = np.random.randint(1, 101, size=(7, 7))
matrix[matrix % 5 == 0] = -5
print(matrix)


[[-5 -5 -5 87 73 67 17]
 [-5 -5 56 39 -5 31 49]
 [-5 53 27 76 93 14 -5]
 [67 62 37 81 57 -5 78]
 [ 4 -5 18 71 43 51 87]
 [ 8 82 77 76 -5 81 98]
 [74  8 37 93 51 17 61]]


In [36]:
# 14. Given arr = np.linspace(0, 2*np.pi, 10), compute sine and cosine values for each element and stack them into a 2D array with shape (10,2).
arr = np.linspace(0, 2*np.pi, 10)
print(arr)
arr[arr % 5 == 0 ] = -5
print(arr)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
[-5.          0.6981317   1.3962634   2.0943951   2.7925268   3.4906585
  4.1887902   4.88692191  5.58505361  6.28318531]


In [37]:
# 15. Create a 5×5 checkerboard pattern (alternating 0s and 1s) using slicing, without manually typing each element.
arr = np.zeros((5,5),dtype = int)
arr[::2,::2] = 1
arr[1::2,1::2] = 1
print(arr)


[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]
